name: bam2tensor
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.9.*
  - conda-forge::cxx-compiler
  - conda-forge::zlib
  - bioconda::samtools
  - bioconda::bedtools
  - bioconda::bcftools
  - pip
  - pip:
      - torch==2.0.1
      - fire==0.5.0
      - pybedtools==0.9.0
      - pysam
      - matplotlib==3.7.1
      - numpy==1.24.3
      - pandas==1.5.3
      - seaborn==0.12.2

